name: Update docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update docs
        run: |
          git submodule update --remote docs
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -a -m "Update docs"
          git push
